---
- include: dynamic.yml
  when: type in ["es", "nuxeo"]
- include: dynamic.yml
  when: kafka and type in ["kafka"]
- include: db.yml
  when: type == "db"
- include: nosqldb.yml
  when: type == "db" and nosqldbprofile != "none"
- include: mongodb.yml
  when: type == "mongodb"
- include: mgmt.yml
  when: type == "mgmt"

