---
aws_region: eu-west-1
elb_name: bench-elb
redis_host: bench.yjr8h8.0001.euw1.cache.amazonaws.com
bucket: nuxeo-devtools-bench
#connect_url: https://nos-preprod-connect.nuxeocloud.com/nuxeo/site/
connect_url: https://connect.nuxeo.com/nuxeo/site/

# do not change the bench tag or update stop/terminate scripts
bench: test
counts:
  nuxeo: 2
  es: 3
  kafka: 1
volsizes:
  nuxeo: 50
  es: 250
  kafka: 250

dbparams:
  mongodb:
    template: mongodb
  pgsql:
    port: 5432
    adminname: template1
    adminuser: nxadmin
    adminpass: nuxeo
    name: bench
    user: bench
    pass: bench
    template: postgresql-quartz-cluster
  oracle12c:
    port: 1521
    adminname: NUXEO
    adminuser: sys
    adminpass: nuxeo
    name: NUXEO
    user: bench
    pass: bench
    template: oracle-quartz-cluster
  mssql:
    port: 1433
    adminname: master
    adminuser: sa
    adminpass: nuxeo
    name: bench
    user: bench
    pass: bench
    template: mssql-quartz-cluster
  mysql:
    port: 3306
    adminname: mysql
    adminuser: root
    adminpass: nuxeo
    name: bench
    user: bench
    pass: bench
    template: mysql
  marklogic:
    port: 8010
    adminport: 8002
    adminname: admin
    adminuser: admin
    adminpass: nuxeo
    name: bench
    user: admin
    pass: nuxeo
    template: marklogic

use_oracle_jdk: false

use_zulu_jdk: true
