---
# Set better hostname
- name: Reset node numbers
  shell: redis-cli -h {{redis_host}} --csv del es_node_number
  run_once: true
- name: Get node number
  shell: redis-cli -h {{redis_host}} --csv incr es_node_number
  register: nodenum
- name: Set hostname
  shell: hostname es{{nodenum.stdout}}
- name: Update /etc/hostname
  shell: echo -n es{{nodenum.stdout}} > /etc/hostname
- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127.0.0.1.*$'
    line: "127.0.0.1 localhost es{{nodenum.stdout}}"

- name: Check if elastic is already setup
  stat: path=/etc/elasticsearch/elasticsearch.yml
  register: stes

# install open jdk 8
- name: Add Open JDK Repository
  apt_repository: repo='ppa:openjdk-r/ppa'
  when: not stes.stat.exists
- name: Install Open JDK 8
  apt: name={{item}} state=latest
  with_items:
    - openjdk-8-jdk
  when: not stes.stat.exists

# install elastic
- name: Add elastic repo key
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
  sudo: yes
  when: not stes.stat.exists
#- name: Add elastic repo 5.x
#  shell: echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
#  sudo: yes
#  when: not stes.stat.exists
- name: Add elastic repo 6.x
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
  sudo: yes
  when: not stes.stat.exists
- name: Install Elasticsearch
  apt:
    name={{item}}
    state=latest
    force=yes
    update_cache=yes
  with_items:
  - elasticsearch
  sudo: yes
- name: EC2 plugin install
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install discovery-ec2 --batch
  when: not stes.stat.exists

# Prepare EBS volume in /opt
- name: Check if EBS volume is mounted
  shell: cat /proc/mounts | grep /dev/xvdf
  changed_when: False
  failed_when: False
  register: mounted
- name: Format EBS volume
  shell: mkfs.ext4 /dev/xvdf
  when: mounted.stdout == ""
- name: Mount EBS volume
  mount: src=/dev/xvdf name=/opt fstype=ext4 state=mounted
  when: mounted.stdout == ""
- name: Create elastic dir
  file: path=/opt/es state=directory owner=elasticsearch group=elasticsearch

# Setup elastic config
- name: Get heap size
  shell: echo "$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1024 / 1024 / 2 ))g"
  register: es_heap
  when: not stes.stat.exists
- name: Setup elastic configuration
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml
  when: not stes.stat.exists
- name: Setup elastic default configuration
  template: src=elasticsearch.j2 dest=/etc/default/elasticsearch
  when: not stes.stat.exists
  notify: Restart elasticsearch

# Setup Diamond
- name: Add Diamond config
  template: src=diamond.j2 dest=/etc/diamond/diamond.conf
- name: Start Diamond
  shell: service diamond restart
