---

# Install tools
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=7200
- name: Upgrade/install tools
  apt: state=latest name={{item}}
  with_items:
  - unzip

# Ensure instance is clean
- name: Check for ES init script
  stat: path=/etc/init.d/elasticsearch
  register: esinit
- name: Stop ES
  shell: /etc/init.d/elasticsearch stop
  when: esinit.stat.exists
- name: Delete /opt/es
  file: path=/opt/es state=absent


# Get ES
- name: Get ES
  get_url:
    url: https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-{{es_version}}.zip
    dest: /tmp/elasticsearch-{{es_version}}.zip

# Extract and setup ES
- name: es user
  user:
    name: es
    shell: /bin/bash
    home: /opt/es
    createhome: yes
    state: present
- name: Limits - nofile
  lineinfile:
    dest: /etc/security/limits.conf
    line: "es - nofile 65536"
- name: Limits - memlock
  lineinfile:
    dest: /etc/security/limits.conf
    line: "es - memlock unlimited"
- name: Unzip ES
  shell: unzip -q -d /opt/es /tmp/elasticsearch-{{es_version}}.zip
  become_user: es
- name: Add symlink to ES
  file: path=/opt/es/elasticsearch src=/opt/es/elasticsearch-{{es_version}} state=link
  become_user: es
- name: Config - cluster name
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*cluster\.name:'
    line: "cluster.name: {{es_cluster}}"
- name: Config - aws region
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*cloud\.aws\.region:'
    line: "cloud.aws.region: {{aws_region}}"
- name: Config - discovery type
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*discovery\.type:'
    line: "discovery.type: ec2"
- name: Config - discovery groups
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*discovery\.ec2\.groups:'
    line: "discovery.ec2.groups: {{security_group}}"
- name: Config - auto attributes
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*cloud\.node\.auto_attributes:'
    line: "cloud.node.auto_attributes: true"
- name: Config - mlockall
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*bootstrap\.mlockall:'
    line: "bootstrap.mlockall: true"
- name: Config - bulk queue size
  lineinfile:
    dest: /opt/es/elasticsearch/config/elasticsearch.yml
    regexp: '^#?\s*threadpool\.bulk\.queue_size:'
    line: "threadpool.bulk.queue_size: 1000"

#- name: Logging - debug
#  lineinfile:
#    dest: /opt/es/elasticsearch/config/logging.yml
#    regexp: '^#?\s*es\.logger\.level:'
#    line: "es.logger.level: DEBUG"
- name: EC2 plugin install
  shell: /opt/es/elasticsearch/bin/plugin -install org.elasticsearch/elasticsearch-cloud-aws/{{ec2_plugin_version}}
  become_user: es
- name: Init script
  copy:
    src: es_init.sh
    dest: /etc/init.d/elasticsearch
    mode: 0755
  register: es_init

# Start ES
- name: Start ES
  shell: /etc/init.d/elasticsearch start

