#!/bin/bash
DAEMON_PATH=/opt/kafka/bin
DAEMON_NAME=kafka
# Check that networking is up.
#[ ${NETWORKING} = "no" ] && exit 0

PATH=$PATH:$DAEMON_PATH

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        echo "Starting $DAEMON_NAME";
        su kafka -c "JMX_PORT=1089 KAFKA_HEAP_OPTS=\"-Xmx4G -Xms4G -Dkafka_mx4jenable=true\" LOG_DIR=\"/opt/kafka\" nohup $DAEMON_PATH/kafka-server-start.sh -daemon /etc/kafka-server.properties > /opt/kafka/kafka.log 2>&1 &"
        ;;
  stop)
        # Stop daemons.
        echo "Shutting down $DAEMON_NAME";
        pid=`ps ax | grep -i 'kafka.Kafka' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          su kafka -c "$DAEMON_PATH/kafka-server-stop.sh"
          sleep 5
          kill -9 $pid
        else
          echo "Kafka was not Running"
        fi
        ;;
  restart)
        $0 stop
        sleep 2
        $0 start
        ;;
  status)
        pid=`ps ax | grep -i 'kafka.Kafka' | grep -v grep | awk '{print $1}'`
        if [ -n "$pid" ]
          then
          echo "Kafka is Running as PID: $pid"
        else
          echo "Kafka is not Running"
        fi
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
esac

exit 0
